theme: jekyll-theme-cayman
title: WCCI2022 IJCNN-SS-5 
description: "Deep Learning for Anomaly Detection: Theory, Algorithms, and Applications"
top_image: https://wcci2022.org/wp-content/uploads/2020/07/WCCI2022-padua-logo.png
layout: page
